### ISSUE TITLE
Goals for the week 47

### ISSUE THREAD

**Issue by UErenReply** [UErenReply/weeklyresults#4]
Goals for this week are: 

- Optional - Look at library like Go Chi, Gorilla mux . Mainly Go Chi

- Create Friday presentation for HTTP test package (10-15min)
 
- Create unit tests for HTTP handlers using HTTP test package

**Comment by tknuestingreply** [comment]
https://pkg.go.dev/net/http/httptest

**Comment by UErenReply** [comment]
I have completed for this week:

Optional - Look at library like Go Chi, Gorilla mux . Mainly Go Chi

Create Friday presentation for HTTP test package (10-15min)

Create unit tests for HTTP handlers using HTTP test package
